### ISSUE TITLE
Hash Inline styles

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/thenewdynamic.com#109]
Critical CSS is great for performance, but for security we need to ensure any inline styles are explicitly allowed in our content security policy. 

We need to generate a hash of generated styles (I believe we can do this with Hugo's integrity function), but the hash goes into the generated Content Security Policy header:

e.g.
`Content-Security-Policy: style-src 'sha256-B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8='`

This issue depends on #108

**Comment by regisphilibert** [comment]
Yes, it's just about calling the style form the _headers output format and printing it's `Data.Fingerprint`

**Comment by regisphilibert** [comment]
I understand what needs to be achieved on the header file side, but when printing the tag? Does it need the matching integrity attribute of attribute?

```html
<style integrity="sha256-YPxff30Qq1ac9coOVBl7f84qO8fhVpeYn2qLmEXlDjU=">
.iub_content h1{
  margin-top: 2rem;
  font-size: 2.25rem;
}
</style>

```

**Comment by budparr** [comment]
The integrity has doesn't have to be printed on the script itself. Just in the header.

**Comment by budparr** [comment]
some background (not the nonce part), see the "If You Absolutely Must Use It…" section of this page: https://www.html5rocks.com/en/tutorials/security/content-security-policy/

**Comment by regisphilibert** [comment]
We tried by capturing the content of the `<style>` tag we use to print critical css, and add its sha to the CSP something like:

`style-src 'self' 'sha256-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';`

But the console log did not like that... We need to see if there's a difference between css contained in <style> tags and `inline css` passed through the `style` attribute of a HTML tag.

**Comment by regisphilibert** [comment]
Finally found the issue. As we were using `.PostProcess` every style assets, this meant their .Content was not really available during the build (so the string returned by `.Content` when accessing them from the AddHeaderGroups partial was something like `_h__Content_whatever` instead of the actually produced content. 

We know avoid doing anything to critical styles from the GetStyleAssets partials as the minification on the printed content (inside the <style>) tag will happen on the HTML level. 

As it turns out, HTML minification of the font style content matches the the minification of the asset content and so does the resulting hash... 

Now this could change if the style was bigger (only fontface decleration for now...)

**Comment by regisphilibert** [comment]
Nope that's not it. So I know the hash matches... now but for some reason I'm getting the same console error. 
Maybe the order matters, will give it another try...

**Comment by regisphilibert** [comment]
Ok I'm giving up for now.

#### The main problem when trying to debug the issues is:
1. We rely on minification to make sure the hash matches. But minification means console error cannot point to the problematic line. If I remove minification then hashes don't match and the produced error might be different.
2. `netlify dev` can only work on server mode which does not match the hashes expected and at any rate it does not seem to take into accounts headers. This means we must push to a branch our changes in order to debug this...

**Comment by budparr** [comment]
So our options are?

- [ ] Don't use inline styles
- [ ] use `unsafe-inline` in our CSP
- [ ] "What's behind door number 3, Bob?"

**Comment by regisphilibert** [comment]
For now we are using `unsafe-inline`. Now if we were not doing critical scripts with <style> we could do:

```
style-src 'self'; style-src-attr 'unsafe-inline';
```
This would at least limit the unsafe inline to the style attributes (which we have on svgs) but restrict <style> tags. There is the [`style-src-elem`] which specifically target elements but it's in experimentation mode and if my hash did not work with `style-src` I doubt it will with this one...

**Comment by budparr** [comment]
Okay. Thanks. Quite a sticky wicket.
